site_name: nanoCEM
nav:
  - Home: index.md
  - Quick start: tutorials.md
  - Output files description: output_format.md
  - Data preparation from raw reads : preparation.md
  - Command line arguments : argument.md
  - Description of statistical features : statistics.md
  - An example for application: example.md
  - Contacts: contact.md
theme: readthedocs